name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Ajusta esto si quieres que se ejecute en diferentes ramas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-website:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: docker push my-website:${{ github.sha }}

    # Aquí puedes agregar pasos para desplegar el contenedor en un servidor si es necesario
